datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/ca_17"
    username: ca_17
    password: supersecret
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
application:
  pagination:
    pageSize: 10