micronaut:
  application:
    name: "Cambalache API"
datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: PostgreSQL
flyway:
  datasources:
    default:
      table: migration
jpa:
  default:
    entity-scan:
      packages:
        - "com.cambalache.api.anuncios.busqueda.domain"
jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ssZ"